name: Native Image

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Native Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.1.0
          native-image: true
      - name: Maven Build
        run:
          mvn clean install -Pnative -DskipTests
      - name: Create Tag
        run: |
          echo "RELEASE_TAG=`cat ./src/main/resources/.version`" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push latest-native
        id: latest-native
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./DockerfileNative
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ secrets.REPO }}:latest-native
      - name: Build and Push ${{ env.RELEASE_TAG }}-native
        id: tag
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./DockerfileNative
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ secrets.REPO }}:${{ env.RELEASE_TAG }}-native
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
